my_recipes:
    resource: "@MyRecipesBundle/Resources/config/routing.yml"
    prefix:   /

recipes_list:
   path: /recipes/
   defaults: {_controller: MyRecipesBundle:Recipe:list }

recipes_show:
   path: /recipes/{recipe_name}
   defaults: {_controller: MyRecipesBundle:Recpies:show } 
