parameters:
#    my_recipes.example.class: My\RecipesBundle\Example

services:
#    my_recipes.example:
#        class: %my_recipes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
